-- Catalogo de permisos (module.action)
INSERT IGNORE INTO permissions (module, action, slug) VALUES
('pages',           'view',    'pages.view'),
('pages',           'create',  'pages.create'),
('pages',           'edit',    'pages.edit'),
('pages',           'delete',  'pages.delete'),
('pages',           'publish', 'pages.publish'),
('posts',           'view',    'posts.view'),
('posts',           'create',  'posts.create'),
('posts',           'edit',    'posts.edit'),
('posts',           'delete',  'posts.delete'),
('posts',           'publish', 'posts.publish'),
('products',        'view',    'products.view'),
('products',        'create',  'products.create'),
('products',        'edit',    'products.edit'),
('products',        'delete',  'products.delete'),
('products',        'publish', 'products.publish'),
('orders',          'view',    'orders.view'),
('orders',          'edit',    'orders.edit'),
('orders',          'approve', 'orders.approve'),
('orders',          'reject',  'orders.reject'),
('sales',           'view',    'sales.view'),
('sales',           'create',  'sales.create'),
('sales',           'cancel',  'sales.cancel'),
('inventory',       'view',    'inventory.view'),
('inventory',       'adjust',  'inventory.adjust'),
('payment_methods', 'view',    'payment_methods.view'),
('payment_methods', 'edit',    'payment_methods.edit'),
('categories',      'view',    'categories.view'),
('categories',      'create',  'categories.create'),
('categories',      'edit',    'categories.edit'),
('categories',      'delete',  'categories.delete'),
('services',        'view',    'services.view'),
('services',        'create',  'services.create'),
('services',        'edit',    'services.edit'),
('services',        'delete',  'services.delete'),
('galleries',       'view',    'galleries.view'),
('galleries',       'create',  'galleries.create'),
('galleries',       'edit',    'galleries.edit'),
('galleries',       'delete',  'galleries.delete'),
('files',           'view',    'files.view'),
('files',           'create',  'files.create'),
('files',           'delete',  'files.delete'),
('sliders',         'view',    'sliders.view'),
('sliders',         'create',  'sliders.create'),
('sliders',         'edit',    'sliders.edit'),
('sliders',         'delete',  'sliders.delete'),
('banners',         'view',    'banners.view'),
('banners',         'create',  'banners.create'),
('banners',         'edit',    'banners.edit'),
('banners',         'delete',  'banners.delete'),
('contacts',        'view',    'contacts.view'),
('contacts',        'edit',    'contacts.edit'),
('contacts',        'delete',  'contacts.delete'),
('social_networks', 'view',    'social_networks.view'),
('social_networks', 'create',  'social_networks.create'),
('social_networks', 'edit',    'social_networks.edit'),
('social_networks', 'delete',  'social_networks.delete'),
('settings',        'view',    'settings.view'),
('settings',        'edit',    'settings.edit'),
('users',           'view',    'users.view'),
('users',           'create',  'users.create'),
('users',           'edit',    'users.edit'),
('users',           'delete',  'users.delete'),
('roles',           'view',    'roles.view'),
('roles',           'create',  'roles.create'),
('roles',           'edit',    'roles.edit'),
('roles',           'delete',  'roles.delete');

-- Rol 2 = admin: todo excepto roles
INSERT IGNORE INTO role_permissions (role_id, permission_id)
SELECT 2, id FROM permissions WHERE module != 'roles';

-- Rol 3 = editor: contenido (pages/posts/products/categories/services/galleries/files/sliders) solo view+create+edit
INSERT IGNORE INTO role_permissions (role_id, permission_id)
SELECT 3, id FROM permissions
WHERE module IN ('pages','posts','products','categories','services','galleries','files','sliders')
  AND action IN ('view','create','edit');
