<?php

declare(strict_types=1);

if (PHP_SAPI !== 'cli') exit("Este seeder solo puede ejecutarse por CLI.\n");

$root = dirname(__DIR__, 2);
require $root . '/app/Helpers/app.php';
require $root . '/app/Core/Database.php';
load_env_file($root . '/.env');
$pdo = Database::connection();

$products = [
  1 => ['name_en'=>'Fermented Cacao Beans','short_description_en'=>'Selected, fermented and dried beans for specialized buyers.','description_en'=>'Cooperative-origin dried cacao, sorted by lot, with moisture and aroma control and traceability back to the producer.','origin_en'=>'Pangoa – Mazamari, Satipo, Junín','variety_en'=>'VRAE 99, VRAE 15, Bellavista and Native','fermentation_en'=>'80% minimum (brown beans)','altitude_en'=>'550 to 1,200 m a.s.l.','certification_en'=>'Fair trade and origin traceability','presentation_en'=>'46 kg jute sacks and 85 g packages','meta_title_en'=>'Fermented Cacao Beans','meta_description_en'=>'Cacao beans with traceability and quality for commercialization.'],
  2 => ['name_en'=>'Roasted Cacao Nibs','short_description_en'=>'Crunchy cacao pieces with an intense aroma for chocolate making and baking.','description_en'=>'Nibs made from selected, roasted and crushed beans for healthy formulations and value-added products.','meta_title_en'=>'Roasted Cacao Nibs','meta_description_en'=>'Cacao nibs for chocolate making, baking and snacks.'],
  3 => ['name_en'=>'Natural Cacao Liquor','short_description_en'=>'Pure cacao mass for making chocolate, coatings and beverages.','description_en'=>'Additive-free cacao liquor, ideal for customers seeking intensity, origin and a distinctive aromatic profile.','meta_title_en'=>'Natural Cacao Liquor','meta_description_en'=>'Cacao liquor for derivatives and chocolate making.'],
  4 => ['name_en'=>'Cacao Butter','short_description_en'=>'A premium derivative for fine chocolate making, natural cosmetics and specialty formulations.','description_en'=>'Butter obtained from selected cacao, intended for food and cosmetic applications.','meta_title_en'=>'Cacao Butter','meta_description_en'=>'Cacao butter for chocolate making and cosmetics.'],
  5 => ['name_en'=>'Cacao Powder','short_description_en'=>'Aromatic cacao powder for beverages, baking, ice cream and healthy cooking.','description_en'=>'Intense-flavored cacao powder intended for culinary use, hot beverages and commercial blends.','meta_title_en'=>'Cacao Powder','meta_description_en'=>'Cacao powder for food and beverages.'],
  6 => ['name_en'=>'Artisan Dark Chocolate','short_description_en'=>'Demonstration bars with a high cacao percentage, inspired by cooperative-origin cacao.','description_en'=>'Dark chocolate made as a demonstration value-added product to showcase the potential of local cacao.','meta_title_en'=>'Artisan Dark Chocolate','meta_description_en'=>'Cooperative-origin dark chocolate.'],
];
$common = ['origin_en'=>'Pangoa – Pangoa, Satipo, Junín','variety_en'=>'VRAE 99, VRAE 15, Bellavista and Native','fermentation_en'=>'80% minimum (brown beans)','altitude_en'=>'550 to 1,200 m a.s.l.','certification_en'=>'Fair trade and origin traceability','presentation_en'=>'46 kg jute sacks and 85 g packages'];
foreach ([2,3,4,5,6] as $id) $products[$id] += $common;

$services = [
  1=>['Cacao Sourcing','Reception, weighing and grading of fresh and dried cacao from partner producers.','Sourcing service with producer-level records, moisture control, initial assessment and lot organization.','Cacao Sourcing','Cacao sourcing with traceability.'],
  2=>['Fermentation and Drying','Technical support to improve bean aroma, color, moisture and yield.','Demonstration post-harvest processing that prioritizes standardization, sensory quality and drying control.','Fermentation and Drying','Post-harvest processing for quality cacao.'],
  3=>['Quality Control','Assessment of moisture, fermentation, defects, aroma and lot-level traceability.','Quality control to segregate lots, reduce commercial risks and prepare products with clear specifications.','Cacao Quality Control','Cacao quality and traceability.'],
  4=>['Processing of Cacao Derivatives','Production of nibs, liquor, butter, powder and demonstration chocolate.','A value-added service designed to showcase the commercial potential of cacao derivatives.','Cacao Derivatives','Processing cacao into derivatives.'],
  5=>['Cooperative Marketing','Buyer engagement and commercial preparation of cacao and derivatives.','Commercial support that connects organized producers with domestic and international customers.','Cacao Marketing','Cooperative sales of cacao and derivatives.'],
  6=>['Producer Training','Technical assistance in harvesting, post-harvest handling, quality and sustainability.','Training to strengthen production skills and improve cacao quality from the farm onward.','Cacao Training','Technical training for producers.'],
];

$postText = [
  1=>['Community Cacao Collection','Producer families organize deliveries of fresh and dried cacao with transparent lot-level records.','Community','Productive Cacao Farms','Technical assistance for productive cacao farms.','farms, producers, cacao',<<<'HTML'
<p>Community cacao collection is the first link in COOPAECA’s cacao value chain. Every week, producer families from different communities deliver their harvest to authorized collection centers, where fresh and dried beans are weighed, graded and recorded by lot before continuing to post-harvest processing.</p><h3>A system designed for transparency</h3><p>Each delivery is documented with the producer’s name, farm of origin, harvest date and exact weight received. This traceability recognizes each member’s effort and supports fair payment: the price each family receives directly reflects the quality and volume supplied, without intermediaries reducing their margin.</p><p>Collection also plays an important social role. Reception centers become meeting points where cooperative technicians provide immediate post-harvest recommendations while producers exchange experiences.</p><h3>From the farm to the collection center</h3><ul><li>Selective harvesting of ripe cacao pods.</li><li>Transport in the shortest possible time to prevent quality loss.</li><li>Individual weighing and recording by producer and lot.</li><li>Initial grading based on moisture and bean condition.</li></ul><p>This organization provides the basis for consistent fermentation and drying processes and ultimately distinguishes COOPAECA cacao in markets that demand verifiable origin.</p>
HTML],
  2=>['Controlled Fermentation','Fermentation and drying processes that improve aroma, color, moisture and commercial yield.','Community','Productive Cacao Farms','Technical assistance for productive cacao farms.','farms, producers, cacao',<<<'HTML'
<p>Along with cacao genetics, fermentation is one of the factors that most strongly influences the bean’s final aroma and flavor profile. At COOPAECA, this process takes place under controlled time, temperature and turning conditions in wooden boxes specifically designed to promote uniform fermentation.</p><h3>Why every variable is controlled</h3><p>During fermentation, yeasts and bacteria transform the sugars in the mucilage surrounding the beans, creating the precursors of chocolate flavor. If the process is too short, the beans remain astringent; if it runs too long, undesirable notes develop. The technical team therefore monitors the internal temperature of the cacao mass daily and turns it at precisely scheduled times.</p><p>The results are directly reflected in commercial value: a properly fermented lot has a uniform brown color, a clean aroma and fewer defects—qualities that fine cacao buyers verify before concluding any negotiation.</p><h3>Stages of the process</h3><ul><li>Filling boxes with freshly extracted wet beans.</li><li>Scheduled turning to aerate and homogenize the mass.</li><li>Temperature control throughout the fermentation cycle.</li><li>Sensory and cut-test evaluation before drying.</li></ul><p>This disciplined post-harvest handling is one reason the cooperative’s cacao can enter export markets with more demanding quality requirements.</p>
HTML],
  3=>['Productive Farms','Support for partner farms to strengthen productivity, traceability and good practices.','Community','Productive Cacao Farms','Technical assistance for productive cacao farms.','farms, producers, cacao',<<<'HTML'
<p>Behind every sack of cacao exported by COOPAECA is a farm, a family and years of steady work in the fields. The productive farm support program seeks to strengthen that connection by providing members with direct technical assistance on their own land.</p><h3>Individual follow-up for every farm</h3><p>A team of agricultural technicians periodically visits partner farms to assess plant health, planting density, pruning and shade practices, and soil conditions. Every visit is recorded, allowing the cooperative to maintain a production history for each family unit and provide specific recommendations suited to its circumstances.</p><p>This support is not limited to agronomy: it also covers harvest records, responsible pest management and the planned renewal of aging plantations, with the aim of sustaining long-term productivity.</p><h3>Benefits for producers</h3><ul><li>Free technical assessment of the farm.</li><li>Agronomic management recommendations adapted to each soil.</li><li>Better origin traceability for export purposes.</li><li>Greater year-to-year production stability.</li></ul><p>Strengthening productive farms ultimately strengthens the cooperative itself: the stronger its agricultural base, the more consistent the supply of quality cacao that COOPAECA can offer buyers.</p>
HTML],
  4=>['Cacao Nibs and Liquor','Demonstration processing of cacao into nibs, liquor and higher value-added derivatives.','Derivatives','Cacao Nibs and Liquor','Value-added cacao derivatives for specialized buyers.','nibs, liquor, derivatives',<<<'HTML'
<p>Beyond dried beans, COOPAECA is developing a demonstration processing line that turns cacao into higher value-added products: roasted nibs and pure cacao liquor, formats that directly showcase the aromatic identity of their Amazonian origin.</p><h3>From bean to nib</h3><p>The process begins by selecting the best fermented and dried lots, which undergo carefully calibrated roasting to highlight the fruity and floral notes characteristic of cacao from the region. After roasting, the beans are winnowed and broken into small pieces: nibs, ready to eat or use in baking and other artisan preparations.</p><p>When those same nibs are ground at low temperatures into a liquid texture, they become cacao liquor, the foundation of all artisan chocolate. Its intense flavor and texture allow buyers to accurately assess the origin’s potential before committing to larger bean purchases.</p><h3>A showcase of quality</h3><ul><li>Roasted nibs ready to eat or use in baking.</li><li>100% pure cacao liquor, with no additives.</li><li>Demonstrations at trade fairs and during visits by international buyers.</li></ul><p>This demonstration processing does not replace cacao bean exports, but it plays a strategic role: it allows customers and visitors to immediately taste the quality behind every lot sourced by the cooperative.</p>
HTML],
  5=>['Technical Training','Practical sessions on harvesting, selection, processing, food safety and post-harvest handling.','Training','Technical Training in Cacao','Producer training to improve cacao quality.','training, producers, quality',<<<'HTML'
<p>Cacao quality is not achieved only on the plant: it is built on the farm through clear technical criteria at every stage of the process. That is why COOPAECA regularly organizes training sessions for producer members and their families.</p><h3>Topics covered in each session</h3><p>Training ranges from identifying the optimal harvest point—recognizing the color and sound of a ripe pod—to properly selecting beans, as well as correctly managing fermentation and drying times. It also includes food-safety modules, which are essential for meeting the requirements of international buyers.</p><p>Each session combines brief theory with hands-on practice: technicians bring bean samples in different conditions so producers can learn to identify defects, moisture levels and the signs of proper fermentation.</p><h3>Impact on final quality</h3><ul><li>Fewer physical defects in delivered beans.</li><li>Better moisture management before collection.</li><li>Greater awareness of food safety and product handling.</li><li>Producers better prepared to meet demanding market requirements.</li></ul><p>For the cooperative, investing in technical training is one of the most direct ways to achieve sustained improvement in the quality of cacao ultimately destined for export.</p>
HTML],
  6=>['Export Quality','Lot assessment for buyers who demand consistency, origin and reliable documentation.','Quality','Export-Quality Cacao','Quality control for traceable, export-ready cacao.','export, traceability, quality',<<<'HTML'
<p>Exporting cacao is not simply a matter of sending sacks to port: it requires compliance with demanding standards for moisture, physical defects and fermentation, along with documentation supporting the origin of every lot. At COOPAECA, export quality control is a continuous process that begins long before shipment.</p><h3>Parameters assessed</h3><p>Before approving a lot for export, the quality control team checks bean moisture—which must remain within strict ranges to prevent mold growth during transport—the bean index, the presence of broken, slaty or moldy beans, and the fermentation profile through cut tests.</p><p>This is complemented by traceability documentation: every export lot must be traceable to the farms and producers from which it originated, a requirement increasingly valued by international buyers committed to the origin and sustainability of their supply chains.</p><h3>A standard that protects everyone</h3><ul><li>Moisture control before final packing.</li><li>Physical and sensory evaluation of every lot.</li><li>Traceability documentation from farm to port.</li><li>Compliance with certifications required by destination markets.</li></ul><p>This level of rigor does more than open commercial opportunities: it also protects the reputation built through years of work by COOPAECA’s producer families.</p>
HTML],
];

$about = ['about_title_en'=>'A cooperative committed to Peruvian cacao','about_body_en'=>'We are an agricultural cooperative dedicated to sourcing, processing and marketing cacao. We work alongside producers to improve quality, prices, traceability and access to new markets.','about_values_en'=>"Transparent sourcing and fair prices for producers\nTraceability from origin to destination\nContinuous improvement in fermentation and drying",'about_more_title_en'=>'We are a cooperative growing alongside Peruvian cacao','about_more_body_en'=>'We are a cooperative dedicated to strengthening the cacao value chain by integrating responsible sourcing, technical assistance, quality control and sustainable marketing. Our work is rooted in our commitment to farming families and to the quality of our local cacao.','about_history_title_en'=>'Our History','about_history_body_en'=>'The cooperative began as an initiative of organized producers seeking better opportunities for their cacao. Over time, we strengthened our sourcing, fermentation, drying and traceability processes to connect the work carried out in the fields with more demanding markets.','about_mission_en'=>'To advance the development of our members through quality services, fair marketing and the continuous improvement of cacao.','about_vision_en'=>'To become a leading cooperative for sustainable, traceable and high-quality cacao.'];

$about = [
    'map_tag_en' => 'Find us',
    'map_title_en' => 'Locate our company',
    'map_description_en' => 'Visit us and discover where the quality of our products begins. We are ready to assist you and provide information about our services, products and business opportunities.',
] + $about;

function fillRow(PDO $pdo, string $table, int $id, array $data): void {
    $sets=[]; $params=[];
    foreach ($data as $column=>$value) { $sets[]="`$column` = CASE WHEN `$column` IS NULL OR TRIM(`$column`) = '' THEN ? ELSE `$column` END"; $params[]=$value; }
    $params[]=$id;
    $pdo->prepare("UPDATE `$table` SET ".implode(', ',$sets).' WHERE id = ?')->execute($params);
}

$pdo->beginTransaction();
try {
    foreach ($products as $id=>$data) fillRow($pdo,'products',$id,$data);
    foreach ($services as $id=>$v) fillRow($pdo,'services',$id,array_combine(['name_en','short_description_en','description_en','meta_title_en','meta_description_en'],$v));
    foreach ($postText as $id=>$v) fillRow($pdo,'posts',$id,array_combine(['title_en','excerpt_en','category_en','meta_title_en','meta_description_en','meta_keywords_en','content_en'],$v));
    foreach ([1=>'Cacao Beans',2=>'Cacao Derivatives'] as $id=>$name) fillRow($pdo,'categories',$id,['name_en'=>$name]);
    $stmt=$pdo->prepare("INSERT INTO settings (setting_key,setting_value) VALUES (?,?) ON DUPLICATE KEY UPDATE setting_value=IF(setting_value IS NULL OR TRIM(setting_value)='',VALUES(setting_value),setting_value)");
    foreach ($about as $key=>$value) $stmt->execute([$key,$value]);
    $pdo->commit();
    echo "Traducciones EN completadas sin sobrescribir valores existentes.\n";
} catch (Throwable $e) {
    if ($pdo->inTransaction()) $pdo->rollBack();
    fwrite(STDERR,"No se aplicaron cambios: {$e->getMessage()}\n"); exit(1);
}
