<?php
/**
 * Detalle completo de un pedido. Parcial compartido entre la pagina completa
 * (orders/show.php) y el fragmento AJAX cargado dentro del modal "Ver pedido"
 * de /orders (OrderController::detail()). Los formularios de Marcar en
 * revision / Aprobar / Rechazar llevan data-ajax-order-action: dentro del
 * modal se envian por fetch (sin salir de la lista); en la pagina completa,
 * ese atributo se ignora y el formulario funciona de forma clasica.
 * Espera: $order, $items, $sale, $receiptDeliveries, $latestReceiptDelivery.
 */
$statusLabels=['pendiente'=>'Pendiente','voucher_enviado'=>'Voucher enviado','en_revision'=>'En revisión','aprobado'=>'Aprobado','rechazado'=>'Rechazado','cancelado'=>'Cancelado'];
$deliveryLabels=['sent'=>'Enviado','failed'=>'Fallido','pending'=>'Pendiente','prepared'=>'Preparado manualmente'];
$deliveryBadges=['sent'=>'ok','failed'=>'off','pending'=>'warn','prepared'=>'muted'];
$canProcess=in_array($order['status'],['pendiente','voucher_enviado','en_revision'],true);
$voucherUrl=url('/orders/voucher/view?id='.(int)$order['id']); $code=display_code('PED',(int)$order['id'],$order['code'] ?? null);
$emailValid=filter_var((string)($order['email']??''),FILTER_VALIDATE_EMAIL)!==false;
?>
<section class="page-card order-detail-page">
 <div class="page-header"><div><div class="order-title-line"><h2><?= e($code) ?></h2><span class="badge <?= $order['status']==='aprobado'?'ok':'muted' ?>"><?= e($statusLabels[$order['status']]??$order['status']) ?></span></div><span>Compra web · S/ <?= number_format((float)$order['total'],2) ?></span></div><a class="button ghost" href="<?= e(url('/orders')) ?>"><?= icon('arrow-left') ?> Volver</a></div>
 <div class="detail-grid"><article class="detail-panel"><h3>Comprador</h3><dl class="detail-list"><div><dt>Nombre</dt><dd><?= e($order['customer_name']) ?></dd></div><div><dt>Documento</dt><dd><?= e($order['document_type'].' '.$order['document_number']) ?></dd></div><div><dt>WhatsApp</dt><dd><?= e($order['whatsapp']?:'-') ?></dd></div><div><dt>Celular</dt><dd><?= e($order['phone']?:'-') ?></dd></div><div><dt>Correo</dt><dd><?= e($order['email']?:'No registrado') ?><?php if(!$emailValid): ?> <span class="badge warn">No válido</span><?php endif ?></dd></div></dl></article>
 <article class="detail-panel"><h3>Dirección</h3><dl class="detail-list"><div><dt>Región</dt><dd><?= e($order['region']) ?></dd></div><div><dt>Provincia</dt><dd><?= e($order['province']) ?></dd></div><div><dt>Distrito</dt><dd><?= e($order['district']) ?></dd></div><div><dt>Dirección</dt><dd><?= e($order['address']) ?></dd></div><div><dt>Referencia</dt><dd><?= e($order['address_reference']?:'-') ?></dd></div></dl></article>
 <article class="detail-panel"><h3>Pago</h3><dl class="detail-list"><div><dt>Método</dt><dd><?= e($order['payment_method']) ?></dd></div><div><dt>Operación</dt><dd><?= e($order['payment_operation_number']) ?></dd></div><div><dt>Total</dt><dd>S/ <?= number_format((float)$order['total'],2) ?></dd></div><div><dt>Voucher</dt><dd><button class="voucher-inline-button" type="button" data-voucher-open data-voucher-url="<?= e($voucherUrl) ?>" data-voucher-code="<?= e($code) ?>" data-voucher-mime="<?= e((string)($order['voucher_mime'] ?? '')) ?>">Ver voucher</button></dd></div></dl></article></div>
 <div class="detail-split"><div class="table-wrap"><table><thead><tr><th>Producto</th><th>SKU</th><th>Presentación</th><th>Cantidad</th><th>Precio</th><th>Subtotal</th></tr></thead><tbody><?php foreach($items as $item): ?><tr><td><?= e($item['product_name']) ?></td><td><?= e($item['product_sku']?:'-') ?></td><td><?= e($item['presentation']?:'-') ?></td><td><?= (int)$item['quantity'] ?></td><td>S/ <?= number_format((float)$item['unit_price'],2) ?></td><td><strong>S/ <?= number_format((float)$item['subtotal'],2) ?></strong></td></tr><?php endforeach ?></tbody></table></div><aside class="detail-panel voucher-panel"><?php if(str_starts_with((string)$order['voucher_mime'],'image/')): ?><a href="<?= e($voucherUrl) ?>" target="_blank" rel="noopener"><img src="<?= e($voucherUrl) ?>" alt="Voucher de pago"></a><?php else: ?><div class="file-preview"><?= icon('file') ?><span><?= e($order['voucher_name']) ?></span></div><?php endif ?></aside></div>
 <?php if($canProcess): ?><section class="process-panel"><div><h3>Validación del pedido</h3><p>Revisa el voucher y el monto antes de continuar.</p></div><div class="action-row"><?php if($order['status']==='voucher_enviado'): ?><form method="post" action="<?= e(url('/orders/review')) ?>" data-lock-submit data-ajax-order-action><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$order['id'] ?>"><button class="button ghost" type="submit">Marcar en revisión</button></form><?php endif ?><button class="button primary" type="button" data-open="approveModal"><?= icon('check-circle') ?> Aprobar pedido</button><button class="button danger" type="button" data-open="rejectModal"><?= icon('x') ?> Rechazar</button></div></section><?php endif ?>
 <?php if($order['status']==='aprobado'&&$sale): ?><section class="receipt-center"><div class="receipt-center-head"><div><span class="eyebrow">NOTA DE VENTA</span><h3><?= $sale['receipt_file_id']?'Documento emitido':'Emisión pendiente' ?></h3><p><?= $sale['receipt_file_id']?'El PDF permanece almacenado y puede consultarse o reenviarse.':'Puede emitirlo manualmente si la emisión automática no concluyó.' ?></p></div><?php if($latestReceiptDelivery): ?><div class="delivery-summary"><span>Último intento</span><strong class="badge <?= e($deliveryBadges[$latestReceiptDelivery['status']]??'muted') ?>"><?= e($deliveryLabels[$latestReceiptDelivery['status']]??$latestReceiptDelivery['status']) ?></strong><small><?= e(date('d/m/Y H:i',strtotime($latestReceiptDelivery['attempted_at']))) ?></small></div><?php endif ?></div>
 <div class="receipt-actions"><a class="button ghost" href="<?= e(url('/sales/show?id='.(int)$sale['id'])) ?>">Ver venta</a><?php if($sale['receipt_file_id']): ?><a class="button info" href="<?= e(url('/orders/receipt/view?id='.(int)$order['id'])) ?>" target="_blank" rel="noopener"><?= icon('file') ?> Ver nota de venta</a><a class="button ghost" href="<?= e(url('/orders/receipt/download?id='.(int)$order['id'])) ?>"><?= icon('download') ?> Descargar</a><?php if(can('orders','approve')): ?><button class="button ghost" type="button" data-open="emailModal"><?= icon('mail') ?> Reenviar correo</button><button class="button whatsapp" type="button" data-open="whatsappModal"><?= icon('whatsapp') ?> WhatsApp manual</button><?php endif ?><?php elseif(can('sales','create')): ?><form method="post" action="<?= e(url('/sales/receipt/issue')) ?>" data-lock-submit><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$sale['id'] ?>"><input type="hidden" name="redirect" value="<?= e(url('/orders/show?id='.(int)$order['id'])) ?>"><button class="button primary" type="submit"><?= icon('printer') ?> Emitir nota de venta</button></form><?php endif ?></div>
 <?php if($receiptDeliveries): ?><div class="delivery-history"><h4>Historial de entregas</h4><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Canal</th><th>Modalidad</th><th>Destinatario</th><th>Estado</th><th>Administrador</th><th>Detalle</th></tr></thead><tbody><?php foreach($receiptDeliveries as $delivery): ?><tr><td><?= e(date('d/m/Y H:i',strtotime($delivery['attempted_at']))) ?></td><td><?= $delivery['channel']==='email'?'Correo':'WhatsApp' ?></td><td><?= $delivery['delivery_mode']==='automatic'?'Automático':'Manual' ?></td><td><?= e($delivery['recipient']?:'-') ?></td><td><span class="badge <?= e($deliveryBadges[$delivery['status']]??'muted') ?>"><?= e($deliveryLabels[$delivery['status']]??$delivery['status']) ?></span></td><td><?= e($delivery['initiated_by_name']?:'Sistema') ?></td><td class="delivery-error"><?= e($delivery['error_message']?:'-') ?></td></tr><?php endforeach ?></tbody></table></div></div><?php endif ?></section><?php endif ?>
</section>
<?php if($canProcess): ?><div class="modal-overlay order-submodal" id="approveModal" style="display:none"><div class="modal-box modal-sm"><div class="modal-header"><h3>Aprobar pedido</h3><button class="modal-close" type="button" data-close>&times;</button></div><form method="post" action="<?= e(url('/orders/approve')) ?>" data-lock-submit data-ajax-order-action><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$order['id'] ?>"><div class="modal-body"><div class="modal-icon success"><?= icon('check-circle') ?></div><p>Al confirmar, el sistema generará la venta, descontará el stock y emitirá la nota de venta.</p><div class="notice-list"><div><?= icon('mail') ?><span><strong>Correo automático</strong>Se intentará enviar a <?= e($emailValid?$order['email']:'un correo válido disponible') ?>.</span></div><div><?= icon('whatsapp') ?><span><strong>WhatsApp manual</strong>Nunca se enviará automáticamente; quedará como opción del administrador.</span></div></div><p class="text-muted">Un fallo de correo no revierte la venta y quedará registrado para reintento.</p></div><div class="modal-footer"><button class="button ghost" type="button" data-close>Cancelar</button><button class="button primary" type="submit"><?= icon('check-circle') ?> Confirmar aprobación</button></div></form></div></div>
<div class="modal-overlay order-submodal" id="rejectModal" style="display:none"><div class="modal-box modal-sm"><div class="modal-header"><h3>Rechazar pedido</h3><button class="modal-close" type="button" data-close>&times;</button></div><form method="post" action="<?= e(url('/orders/reject')) ?>" data-lock-submit data-ajax-order-action><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$order['id'] ?>"><div class="modal-body"><p>Indica el motivo para dejar constancia.</p><label>Motivo de rechazo<input class="form-control" name="admin_notes" placeholder="Ej. Voucher ilegible o monto incorrecto" required></label></div><div class="modal-footer"><button class="button ghost" type="button" data-close>Cancelar</button><button class="button danger" type="submit">Confirmar rechazo</button></div></form></div></div><?php endif ?>
<?php if($order['status']==='aprobado'&&$sale&&$sale['receipt_file_id']&&can('orders','approve')): ?><div class="modal-overlay order-submodal" id="emailModal" style="display:none"><div class="modal-box modal-sm"><div class="modal-header"><h3>Reenviar nota de venta</h3><button class="modal-close" type="button" data-close>&times;</button></div><form method="post" action="<?= e(url('/orders/receipt/email')) ?>" data-lock-submit><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$order['id'] ?>"><div class="modal-body"><p>Se adjuntará el PDF y el resultado quedará en el historial.</p><label>Correo electrónico<input class="form-control" type="email" name="email" value="<?= e($order['email']?:'') ?>" placeholder="cliente@correo.com" required></label></div><div class="modal-footer"><button class="button ghost" type="button" data-close>Cancelar</button><button class="button primary" type="submit"><?= icon('mail') ?> Enviar correo</button></div></form></div></div>
<div class="modal-overlay order-submodal" id="whatsappModal" style="display:none"><div class="modal-box modal-sm"><div class="modal-header"><h3>Preparar envío por WhatsApp</h3><button class="modal-close" type="button" data-close>&times;</button></div><form method="post" action="<?= e(url('/orders/receipt/whatsapp')) ?>" target="_blank" data-lock-submit><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$order['id'] ?>"><div class="modal-body"><div class="manual-warning"><?= icon('whatsapp') ?><p><strong>Envío completamente manual</strong>Se abrirá WhatsApp con un mensaje preparado. Debes adjuntar el PDF descargado y pulsar Enviar.</p></div><label>Número de WhatsApp<input class="form-control" type="tel" name="whatsapp" value="<?= e($order['whatsapp']?:$order['phone']) ?>" required></label></div><div class="modal-footer"><button class="button ghost" type="button" data-close>Cancelar</button><button class="button whatsapp" type="submit"><?= icon('whatsapp') ?> Abrir WhatsApp</button></div></form></div></div><?php endif ?>
