CREATE TABLE IF NOT EXISTS payment_methods (
    id             INT AUTO_INCREMENT PRIMARY KEY,
    name           VARCHAR(120) NOT NULL,
    type           ENUM('bank_transfer','digital_wallet','other') NOT NULL DEFAULT 'other',
    account_label  VARCHAR(160) NULL,
    account_number VARCHAR(120) NULL,
    holder_name    VARCHAR(160) NULL,
    instructions   TEXT NULL,
    qr_image_id    INT NULL,
    is_active      TINYINT(1) NOT NULL DEFAULT 1,
    position       INT NOT NULL DEFAULT 0,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_methods_qr_file FOREIGN KEY (qr_image_id) REFERENCES files(id) ON DELETE SET NULL,
    INDEX idx_payment_methods_active_position (is_active, position)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orders (
    id                         INT AUTO_INCREMENT PRIMARY KEY,
    code                       VARCHAR(30) NOT NULL,
    source                     ENUM('web','whatsapp','phone','manual') NOT NULL DEFAULT 'web',
    status                     ENUM('pendiente','voucher_enviado','en_revision','aprobado','rechazado','cancelado') NOT NULL DEFAULT 'voucher_enviado',
    customer_name              VARCHAR(200) NOT NULL,
    document_type              ENUM('DNI','RUC') NOT NULL,
    document_number            VARCHAR(11) NOT NULL,
    phone                      VARCHAR(20) NULL,
    whatsapp                   VARCHAR(20) NOT NULL,
    email                      VARCHAR(180) NULL,
    region                     VARCHAR(120) NOT NULL,
    province                   VARCHAR(120) NOT NULL,
    district                   VARCHAR(120) NOT NULL,
    address                    VARCHAR(255) NOT NULL,
    address_reference          VARCHAR(255) NULL,
    payment_method             VARCHAR(80) NOT NULL,
    payment_operation_number   VARCHAR(60) NOT NULL,
    voucher_file_id            INT NOT NULL,
    subtotal                   DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    total                      DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    customer_notes             TEXT NULL,
    admin_notes                TEXT NULL,
    ip_address                 VARCHAR(45) NULL,
    user_agent                 VARCHAR(255) NULL,
    approved_by                INT NULL,
    approved_at                DATETIME NULL,
    rejected_at                DATETIME NULL,
    cancelled_at               DATETIME NULL,
    created_at                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uq_orders_code UNIQUE (code),
    CONSTRAINT fk_orders_voucher_file FOREIGN KEY (voucher_file_id) REFERENCES files(id),
    CONSTRAINT fk_orders_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_orders_status_created (status, created_at),
    INDEX idx_orders_document (document_type, document_number),
    INDEX idx_orders_whatsapp (whatsapp),
    INDEX idx_orders_payment_operation (payment_operation_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_items (
    id            INT AUTO_INCREMENT PRIMARY KEY,
    order_id      INT NOT NULL,
    product_id    INT NOT NULL,
    product_name  VARCHAR(180) NOT NULL,
    product_sku   VARCHAR(80) NULL,
    presentation  VARCHAR(255) NULL,
    quantity      INT NOT NULL,
    unit_price    DECIMAL(10,2) NOT NULL,
    subtotal      DECIMAL(10,2) NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id),
    INDEX idx_order_items_order (order_id),
    INDEX idx_order_items_product (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sales (
    id                         INT AUTO_INCREMENT PRIMARY KEY,
    code                       VARCHAR(30) NOT NULL,
    order_id                   INT NULL,
    source                     ENUM('web','whatsapp','phone','manual') NOT NULL DEFAULT 'web',
    status                     ENUM('confirmada','anulada','entregada') NOT NULL DEFAULT 'confirmada',
    customer_name              VARCHAR(200) NOT NULL,
    document_type              ENUM('DNI','RUC') NOT NULL,
    document_number            VARCHAR(11) NOT NULL,
    phone                      VARCHAR(20) NULL,
    whatsapp                   VARCHAR(20) NOT NULL,
    email                      VARCHAR(180) NULL,
    payment_method             VARCHAR(80) NOT NULL,
    payment_operation_number   VARCHAR(60) NOT NULL,
    voucher_file_id            INT NULL,
    subtotal                   DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    total                      DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    confirmed_by               INT NULL,
    confirmed_at               DATETIME NULL,
    cancelled_by               INT NULL,
    cancelled_at               DATETIME NULL,
    created_at                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uq_sales_code UNIQUE (code),
    CONSTRAINT uq_sales_order UNIQUE (order_id),
    CONSTRAINT fk_sales_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,
    CONSTRAINT fk_sales_voucher_file FOREIGN KEY (voucher_file_id) REFERENCES files(id) ON DELETE SET NULL,
    CONSTRAINT fk_sales_confirmed_by FOREIGN KEY (confirmed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_sales_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_sales_status_created (status, created_at),
    INDEX idx_sales_document (document_type, document_number),
    INDEX idx_sales_payment_operation (payment_operation_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sale_items (
    id            INT AUTO_INCREMENT PRIMARY KEY,
    sale_id       INT NOT NULL,
    product_id    INT NOT NULL,
    product_name  VARCHAR(180) NOT NULL,
    product_sku   VARCHAR(80) NULL,
    presentation  VARCHAR(255) NULL,
    quantity      INT NOT NULL,
    unit_price    DECIMAL(10,2) NOT NULL,
    subtotal      DECIMAL(10,2) NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sale_items_sale FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE,
    CONSTRAINT fk_sale_items_product FOREIGN KEY (product_id) REFERENCES products(id),
    INDEX idx_sale_items_sale (sale_id),
    INDEX idx_sale_items_product (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stock_movements (
    id              INT AUTO_INCREMENT PRIMARY KEY,
    product_id      INT NOT NULL,
    movement_type   ENUM('entrada_inicial','entrada_manual','salida_venta','ajuste_manual','anulacion_venta','devolucion') NOT NULL,
    quantity        INT NOT NULL,
    stock_before    INT NULL,
    stock_after     INT NULL,
    reference_type  ENUM('order','sale','manual') NOT NULL DEFAULT 'manual',
    reference_id    INT NULL,
    notes           TEXT NULL,
    created_by      INT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stock_movements_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_stock_movements_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_stock_movements_product_created (product_id, created_at),
    INDEX idx_stock_movements_reference (reference_type, reference_id),
    INDEX idx_stock_movements_type (movement_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ubigeo (
    id              INT AUTO_INCREMENT PRIMARY KEY,
    department_code VARCHAR(2) NOT NULL,
    department_name VARCHAR(120) NOT NULL,
    province_code   VARCHAR(4) NOT NULL,
    province_name   VARCHAR(120) NOT NULL,
    district_code   VARCHAR(6) NOT NULL,
    district_name   VARCHAR(120) NOT NULL,
    UNIQUE KEY uq_ubigeo_district (district_code),
    INDEX idx_ubigeo_department (department_code, department_name),
    INDEX idx_ubigeo_province (province_code, province_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO payment_methods (name, type, account_label, instructions, is_active, position) VALUES
('Transferencia bancaria', 'bank_transfer', 'Cuenta bancaria', 'Adjunta el voucher con el numero de operacion.', 1, 10),
('Yape', 'digital_wallet', 'Billetera digital', 'Adjunta la captura de pago con el numero de operacion.', 1, 20),
('Plin', 'digital_wallet', 'Billetera digital', 'Adjunta la captura de pago con el numero de operacion.', 1, 30);
